Add gofmt CI check (#51)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -29,6 +29,10 @@ jobs:
       - name: Get dependencies
         run: go get -v -t -d ./...
 
+        # designed to only run on linux
+      - name: Format Check
+        run: if [ $(gofmt -l -s . | wc -l) -ne 0 ]; then echo "fmt failed"; exit 1; fi
+
       - name: Build
         run: go build -v ./src/msal
 
